# Font
font_family      JetBrains Mono Nerd Font
font_size 12.0

# kitty_mod ctrl+alt

# Cursor
cursor_shape beam
cursor_trail 1

confirm_os_window_close 0

# Use fish shell
shell fish

map ctrl+enter new_os_window_with_cwd
map ctrl+shift+enter new_window_with_cwd

map ctrl+left neighboring_window left
map shift+left move_window left
map ctrl+down neighboring_window down
map shift+down move_window down
map ctrl+right neighboring_window right
map shift+right move_window right
map ctrl+up neighboring_window up
map shift+up move_window up

map ctrl+shift+q close_window
map ctrl+shift+w close_tab

map ctrl+shift+f launch --type=overlay --allow-remote-control --stdin-source=@screen_scrollback kitty +kitten ~/.config/kitty/search.py

# Copy
# map ctrl+c    copy_or_interrupt

# map ctrl+v paste_from_clipboard

# map alt+shift+enter launch kitty

enabled_layouts tall:bias=50;full_size=1;mirrored=false

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

include dank-tabs.conf
include dank-theme.conf
